json_rpc_urls:
  - https://eth.llamarpc.com/sk_llama_252714c1e64c9873e3b21ff94d7f1a3f
  - https://mainnet.infura.io/v3/5f38fb376e0548c8a828112252a6a588
pool_addr: 0x88e6a0c2ddd26feeb64f039a2c41296fcb3f5640
start_ts: 2023-01-01T00:00:00Z
end_ts: 2023-02-28T23:59:59Z
chunk_size_blocks: 200
parallel_workers: 8
batch_receipt_size: 100
checkpoint_path: data/univ3_checkpoint.json
out_dir: data/univ3_{pool}
skip_gas_data: true
compute_price_column: true
